version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fintech_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_scoring_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fintech_api
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_scoring_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: fintech_streamlit
    restart: always
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    ports:
      - "8501:8501"

volumes:
  postgres_data: